### ISSUE TITLE
v0.1.0 punch list

### ISSUE THREAD

**Issue by jefflunt** [jefflunt/mini-pubsub#52]
The first version that I'll use locally to test must have the following issues taken care of:

* [x] #16 - `Sender` error handling
* [x] #50 - `UDPSender`
* [x] #51 - `UDPReceiver`
* [x] #54 - Crash when sending to non-existent channel
* [x] #55 - Remove rubocop from Gemfile
* [x] #56 - `.gitignore` the `.bundle/` folder
* [x] #57 - Indent router output differently
* [x] #58 - Dump receiver on startup

This should be enough to start for my own purposes.

**Comment by jefflunt** [comment]
Released. https://github.com/jefflunt/mini-pubsub/releases/tag/0.1.0
